ecomercepro/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
    ]

ecomercepro/ecomercepro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include("shop.urls")),
    path('search/', include("search_app.urls")),
    path('cart/', include("cart.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecomercepro/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.SearchResult, name='SearchResult')
]

ecomercepro/shop/urls.py
from . import views
from django.urls import path

app_name = 'shop'
urlpatterns = [

    path('', views.allProCat, name='allProCat'),
    path('<slug:c_slug>/', views.allProCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:pro_slug>/', views.proDetails, name='prodcatdetails'),
]

ecomercepro/cart/models.py
from django.db import models
from shop.models import product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItems(models.Model):
    product = models.ForeignKey(product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItems'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecomercepro/search_app/models.py
from django.db import models

# Create your models here.

ecomercepro/shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:product_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def get_url(self):
        return reverse('shop:prodcatdetails', args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecomercepro/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import product
from .models import Cart, CartItems
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    products = product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItems.objects.get(product=products, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItems.DoesNotExist:
        cart_item = CartItems.objects.create(
            product=products,
            quantity=1,
            cart=cart,
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItems.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    products=get_object_or_404(product,id=product_id)
    cart_item=CartItems.objects.get(product=products,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    products=get_object_or_404(product,id=product_id)
    cart_item=CartItems.objects.get(product=products,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecomercepro/search_app/views.py
from django.shortcuts import render
from shop.models import product
from django.db.models import Q


# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'product': products})

ecomercepro/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import category, product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.
def allProCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(category, slug=c_slug)
        products_list = product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, 'category.html', {'category': c_page, 'product': products})


def proDetails(request, c_slug, pro_slug):
    try:
        prod = product.objects.get(category__slug=c_slug, slug=pro_slug)
    except Exception as q:
        raise q
    return render(request, 'product.html', {'product': prod})

ecomercepro/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hurricane&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    </div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecomercepro/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    this is cart page.proceed to review your items and place the order
{% endblock %}
{% block title %}
   cart organi company pvt lmt
{% endblock %}
 {% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">your shopping cart is empty</h1>
        <p class="text-center">Please Click<a href="{% url 'shop:allProCat' %}">HERE</a>to continue shopping</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">your shopping cart </h1>
        <br>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>

                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href=" cart_item.product.get_absolute_url "><img src="{{cart_item.product.image.url}}" alt="" height="100rem" width="100rem" class="float-left rounded custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product_name}}
                        <br>
                        vgs:{{cart_item.product_id}}
                        <br>
                        price:${{cart_item.product.price}}
                        <br>
                        qty:{{cart_item.quantity}} x ${{cart_item.product.price}}
                    </td>
                    <td>
                        ${{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity > cart_item.product.stock %}
                    <td>
                         <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">  <i class="fa fa-plus custom_icon">  </i></a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}"class="custom_a">  <i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}"class="custom_icon">  <i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% else %}
                     <td>
                         &nbsp;<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    check out
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    please your shopping are items before proceeding with the order payment.

                </td>
            </tr>
            <tr>
                <td class="text-left">
                    your total amount is <strong>{{ total }}</strong>

                </td>
            </tr>

            </tbody>
        </table>
        <div class="mx-auto">
            <a href="" class="btn btn-success btn-block my_custom_button">payment now</a>
            <a href="{% url 'shop:allProCat' %}" class="btn btn-secondary btn-block my_custom_button">continue shopping</a>
        </div>

    {% endif %}

  </div>

 </div>
</div>



{% endblock %}

ecomercepro/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.Description|truncatewords:155 }}
    {% else %}
        welcome to organi store where you can buy natural product..
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }}--organi store
    {% else %}
        see our new collection--organi store
    {% endif %}
{% endblock %}
 {% block content %}

 {% if category %}
  <div>
      <div class="row my_row">
            <div class="mx_auto">
                <p><a href="{% url 'shop:allProCat' %}" >all product of collections</a></p>
            </div>
      </div>
  </div>
 {% endif %}
{% if category %}
    <div class="mx_auto">
         <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" width="100%">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
{% else %}
    <div>
        <img class="my_image my_image_padding "  src="{% static 'img/banner.png'%}" alt="our product" >
    </div>
   <br>
<div>
        <h1 class="text-center my-title">
        our product collection
        </h1>
        <p class="text-center">Science and Technology: Nature and scope of Science and Technology, Relevance of S&T,
National policy on S&T and innovations, Basics of everyday science, Human body, Public
Health and Community Medicine, Food and Nutrition, Health Care. Institutes and
Organization in India promoting integration of S&T and Innovation, their activities and
contributions, Contribution of Prominent Indian Scientists</p>
</div>
{% endif %}
    <div class="container">
        <div class="row mx_auto">
         {% for product in product.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4">
                <div class="card text-center" style="min-width:18rem; height:25rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top  my_image" src="{{product.image.url}}" alt="{{product.name}}" width="250rem" height="250rem" ></a>
                        <div class="card-body">
                          <h4>{{product.name}}</h4>
                          <p>{{product.price}}</p>
                        </div>
                </div>
            </div>
         {% endfor %}
            <div>
                <div class="mx-auto">
                    {% if product.paginator.num_pages > 1 %}
                    <hr>
                    <div class="text-center">
                        {% for pg in product.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if product.number == pg %} active{% endif %}">{{pg}}</a>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            <br>
            </div>
        </div>
    </div>
{% endblock %}

ecomercepro/templates/footer.html
<div class="footer navbar-fixed-bottom   my-footer">
    <p class="text-center">&copy; right Organi pvt ltd. All right reserved</p>
</div>

ecomercepro/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:allProCat' %}"> <img src="{% static 'img/logo.png'%}" alt="logimage" width="130px" height="130px"></a>
    </center>
</header>

ecomercepro/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allProCat' %}">all product</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>[{{item_count}}]</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class='fa fa-search'></i></button>
      </form>
    </div>
  </div>
</nav>

ecomercepro/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.Description|truncatewords:155 }}

{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }}--Faaz store

    {% endif %}
{% endblock %}
 {% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'shop:allProCat' %}">home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}} </p>

    </div>

<div class="container">
<br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt={{product.name}}>
            </div>
        </div>

         <div class="col-12 col-sm-12 col-md-12 col-lg-6">
          <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>{{product.price}}</p>
            <h3 class="my_title">product description</h3>
            <p class="text-justify my_prod_title">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>out of stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
            {% endif %}
          </div>
       </div>

    </div>
</div>
</div>
{% endblock %}

ecomercepro/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

 we have fresh vegetables and fruits
{% endblock %}
{% block title %}
   search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">you have search for <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
         {% for product in product %}
            <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4">
                <div class="card text-center" style="min-width:18rem; height:30rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top  my_image" src="{{product.image.url}}" alt="{{product.name}}"  height="200rem" ></a>
                        <div class="card-body">
                          <h4>{{product.name}}</h4>
                          <p>{{product.price}}</p>
                        </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">no result found</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}